on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myaks2022.azurecr.io
        username: ${{ secrets.acr_myaks2022_username }}
        password: ${{ secrets.acr_myaks2022_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/eng/update-dependencies" -f  "eng/update-dependencies/Dockerfile" -t myaks2022.azurecr.io/myaks:${{ github.sha }} --label dockerfile-path=eng/update-dependencies/Dockerfile
        docker push myaks2022.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksb1d1-dotnet | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksb1d1-dotnet`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksb1d1-dotnet
        container-registry-url: myaks2022.azurecr.io
        container-registry-username: ${{ secrets.acr_myaks2022_username }}
        container-registry-password: ${{ secrets.acr_myaks2022_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksb1d1-dotnet
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          myaks2022.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth
