on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myacr202207.azurecr.io
        username: ${{ secrets.acr_myacr202207_username }}
        password: ${{ secrets.acr_myacr202207_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/eng/update-dependencies" -f  "eng/update-dependencies/Dockerfile" -t myacr202207.azurecr.io/myaks:${{ github.sha }} --label dockerfile-path=eng/update-dependencies/Dockerfile
        docker push myacr202207.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaks85f3-test | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaks85f3-test`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaks85f3-test
        container-registry-url: myacr202207.azurecr.io
        container-registry-username: ${{ secrets.acr_myacr202207_username }}
        container-registry-password: ${{ secrets.acr_myacr202207_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaks85f3-test
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myacr202207.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth
